source ~/.vim/config/colorschemes/github.vim
source ~/.vim/config/colorschemes/solarized.vim
source ~/.vim/config/colorschemes/xoria256.vim
source ~/.vim/config/custom/mail.vim
source ~/.vim/config/custom/ui.vim
source ~/.vim/config/custom/window.vim
source ~/.vim/config/editing/align.vim
source ~/.vim/config/editing/autoclose.vim
source ~/.vim/config/editing/dokuwiki.vim
source ~/.vim/config/editing/gundo.vim
source ~/.vim/config/editing/indent-guides.vim
source ~/.vim/config/editing/latex.vim
source ~/.vim/config/editing/matchit.vim
source ~/.vim/config/editing/neocomplcache.vim
source ~/.vim/config/editing/pandoc.vim
source ~/.vim/config/editing/supertab.vim
source ~/.vim/config/editing/surround.vim
source ~/.vim/config/editing/textile.vim
source ~/.vim/config/editing/textobj.vim
source ~/.vim/config/editing/unimpaired.vim
source ~/.vim/config/general/ack.vim
source ~/.vim/config/general/gist.vim
source ~/.vim/config/general/powerline.vim
source ~/.vim/config/general/vim-pasta.vim
source ~/.vim/config/general/vim-task.vim
source ~/.vim/config/general/vitality.vim
source ~/.vim/config/general/zoomwin.vim
source ~/.vim/config/navigation/file/easymotion.vim
source ~/.vim/config/navigation/tree/bufexplorer.vim
source ~/.vim/config/navigation/tree/ctrlp.vim
source ~/.vim/config/navigation/tree/lusty_juggler.vim
source ~/.vim/config/navigation/tree/nerdtree.vim
source ~/.vim/config/navigation/tree/rooter.vim
source ~/.vim/config/programming/general/fugitive.vim
source ~/.vim/config/programming/general/git_gutter.vim
source ~/.vim/config/programming/general/gitv.vim
source ~/.vim/config/programming/general/ragtag.vim
source ~/.vim/config/programming/general/scala.vim
source ~/.vim/config/programming/general/tagbar.vim
source ~/.vim/config/programming/general/tcomment.vim
source ~/.vim/config/programming/general/xml.vim
source ~/.vim/config/programming/html_css/haml.vim
source ~/.vim/config/programming/html_css/zencoding.vim
source ~/.vim/config/programming/javascript/jquery.vim
source ~/.vim/config/programming/javascript/jshint.vim
source ~/.vim/config/programming/javascript/vim-coffeescript.vim
source ~/.vim/config/programming/javascript/vim-handlebars.vim
source ~/.vim/config/programming/javascript/vim-javascript.vim
source ~/.vim/config/programming/javascript/vim-jst.vim
source ~/.vim/config/programming/php/phpcomplete.vim
source ~/.vim/config/programming/php/piv.vim
source ~/.vim/config/programming/php/twig.vim
source ~/.vim/config/programming/ruby_rails/cucumber.vim
source ~/.vim/config/programming/ruby_rails/rails.vim
source ~/.vim/config/programming/ruby_rails/refactor.vim
source ~/.vim/config/programming/ruby_rails/rspec.vim
source ~/.vim/config/programming/javascript/jquery.vim
source ~/.vim/config/programming/javascript/vim-coffeescript.vim
source ~/.vim/config/programming/javascript/vim-javascript.vim
source ~/.vim/config/programming/javascript/jshint.vim
source ~/.vim/config/programming/javascript/vim-handlebars.vim
source ~/.vim/config/programming/javascript/vim-jst.vim
source ~/.vim/config/programming/general/tcomment.vim
source ~/.vim/config/programming/general/xml.vim
source ~/.vim/config/programming/general/ragtag.vim
source ~/.vim/config/programming/general/tagbar.vim
source ~/.vim/config/programming/general/scala.vim
source ~/.vim/config/programming/general/fugitive.vim
source ~/.vim/config/programming/general/gitv.vim
source ~/.vim/config/programming/general/git_gutter.vim
source ~/.vim/config/general/ack.vim
source ~/.vim/config/general/powerline.vim
source ~/.vim/config/general/vim-task.vim
source ~/.vim/config/general/vitality.vim
source ~/.vim/config/general/zoomwin.vim
source ~/.vim/config/general/vim-pasta.vim
source ~/.vim/config/custom/ui.vim
source ~/.vim/config/custom/window.vim
source ~/.vim/config/colorschemes/xoria256.vim
source ~/.vim/config/colorschemes/github.vim
source ~/.vim/config/colorschemes/solarized.vim
source ~/.vim/config/editing/surround.vim
source ~/.vim/config/editing/autoclose.vim
source ~/.vim/config/editing/indent-guides.vim
source ~/.vim/config/editing/supertab.vim
source ~/.vim/config/editing/textile.vim
source ~/.vim/config/editing/unimpaired.vim
source ~/.vim/config/editing/pandoc.vim
source ~/.vim/config/editing/neocomplcache.vim
source ~/.vim/config/editing/matchit.vim
source ~/.vim/config/editing/latex.vim
source ~/.vim/config/editing/gundo.vim
source ~/.vim/config/editing/align.vim
source ~/.vim/config/editing/dokuwiki.vim
source ~/.vim/config/editing/textobj.vim
